[package]
name = "run-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fuse-protocol = { workspace = true }
servyi-servatui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
libc = "0.2"

[dev-dependencies]
tempfile = "3"
